import type {
  Assignment,
  Concept,
  Course,
  CoverageItem,
  Edge,
  Edition,
  Question,
  ScheduleEvent,
  Source,
} from '../core/schema';

export const snapshot = {
  date: '2026-10-05',
  term: 'Fall 2026',
  vaultCommit: '01c9644647ee197de2a4e06f004a5d1c77535f28',
  timezone: 'America/Vancouver',
};
export const courses: Course[] = [
  {
    id: 'physics',
    title: 'Physics 11',
    shortTitle: 'Physics',
    symbol: 'φ',
    description:
      'Describe motion. Make the signs, units and graphs tell the same story.',
    units: [
      { id: 'basic-skills', title: 'Unit 0 · Basic Skills', status: 'review' },
      { id: 'kinematics', title: 'Unit 1 · Kinematics', status: 'current' },
    ],
  },
  {
    id: 'life-sciences',
    title: 'Life Sciences 11',
    shortTitle: 'Life Sciences',
    symbol: '↟',
    description:
      'Read the evidence for life, its history and its relationships.',
    units: [
      {
        id: 'classification',
        title: 'Chapter 18 · Classification',
        status: 'review',
      },
      {
        id: 'origins',
        title: 'Chapter 17 · Origins & Fossil Record',
        status: 'current',
      },
      {
        id: 'microorganisms',
        title: 'Chapter 19 · Viruses, Bacteria & Disease',
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'japanese',
    title: 'Introductory Japanese 11',
    shortTitle: 'Japanese',
    symbol: 'あ',
    description:
      'Connect a sound, a written form and a situation. Then use it.',
    units: [
      { id: 'writing', title: 'Writing systems & sounds', status: 'current' },
      { id: 'greetings', title: 'Basics & greetings', status: 'current' },
    ],
  },
  {
    id: 'chemistry',
    title: 'Chemistry 11',
    shortTitle: 'Chemistry',
    symbol: '↔',
    description:
      'Follow the electrons: from measurement to atoms, bonds and shape.',
    units: [
      {
        id: 'measurement',
        title: 'Measurement & scientific skills',
        status: 'review',
      },
      { id: 'atomic', title: 'Atomic structure & electrons', status: 'review' },
      { id: 'bonding', title: 'Periodic trends & bonding', status: 'current' },
      {
        id: 'shape',
        title: 'Lewis structures & molecular shape',
        status: 'current',
      },
    ],
  },
];
export const editions: Edition[] = courses.map((c, i) => ({
  id: `${c.id}-fall-2026`,
  course: c.id,
  teacher: ['Mr. Wadson', 'J. Bleecker', 'McNeill-sensei', 'Mrs. Cote'][i],
  term: 'Fall 2026',
  period: i + 1,
  start: '2026-09-08',
  end: '2027-01-29',
  status: 'active',
  verified: snapshot.date,
  currentUnit: ['kinematics', 'origins', 'greetings', 'bonding'][i],
  notes: [
    'The classroom board controls dates. A formula sheet is provided: practise choosing, rearranging and interpreting equations.',
    'Teacher calendar rechecked Oct. 5. C17 test Oct. 7; C19 quiz Oct. 9. Chapter 19 lessons remain pending content review.',
    'Weekly vocabulary/kana checks are expected, but no future quiz dates are confirmed. Independent study only: AI and translators are prohibited for submitted class work.',
    'Oct. 5 quiz: notes through page 24 only. Lewis structures and molecular shape are taught content beyond that quiz boundary. Oct. 16 test scope remains unconfirmed. A clean data booklet is provided.',
  ][i],
  resources: [
    ['https://cwadson.wixsite.com/mrwadson/physics-11-1'],
    [
      'https://sites.google.com/view/ecl-life-sciences-11/home',
      'https://calendar.google.com/calendar/embed?src=q87773ofbdnsahhi3vmatr59t0%40group.calendar.google.com&ctz=America%2FVancouver',
    ],
    ['https://marugoto.jpf.go.jp/en/e-learning/index.html'],
    [
      'https://mrstcote.wordpress.com/',
      'https://curriculum.gov.bc.ca/curriculum/science/11/chemistry',
    ],
  ][i],
}));

export const sources: Source[] = [
  {
    id: 'vault-physics',
    title: 'Current Physics notes & board-derived assessment update',
    type: 'vault-notes',
    reference:
      'Physics 11 / Unit 0, Unit 1, Kinematics Test Prep (updated Oct. 5)',
    author: 'Jovan Pahal; class evidence from Mr. Wadson',
    checked: snapshot.date,
    rights: 'link-only',
    status: 'snapshot',
    notes:
      'Original atlas explanations and examples only. Private grade and returned-work data excluded.',
  },
  {
    id: 'vault-chemistry',
    title: 'Chemistry student study guide & current class-note scope',
    type: 'vault-notes',
    reference:
      'Chemistry 11 / Student Study Guide Insights; Oct. 4 notes; Resources and Calendar (Oct. 5)',
    author: 'Jovan Pahal; class evidence from Mrs. Cote',
    checked: snapshot.date,
    rights: 'link-only',
    status: 'snapshot',
    notes:
      'No teacher worksheet, textbook page or assessment is reproduced. Exact rounding-tie convention remains unverified and is not assumed.',
  },
  {
    id: 'vault-life',
    title: 'Chapter 18 & Chapter 17 class evidence',
    type: 'vault-notes',
    reference:
      'Life Sciences 11 / Units / Chapter 18 and Chapter 17; Oct. 4 C17 scope capture',
    author: 'Jovan Pahal; class evidence from J. Bleecker',
    checked: snapshot.date,
    rights: 'link-only',
    status: 'snapshot',
    notes:
      'Original explanations preserve local six-kingdom terminology while correcting domain Archaea. No answer keys or private performance details.',
  },
  {
    id: 'vault-japanese',
    title: 'Writing systems & current 18-item basics list',
    type: 'vault-notes',
    reference:
      'Introductory Japanese 11 / Sept. 23 Writing Systems; Course Outline and Policies (Oct. 2)',
    author: 'Jovan Pahal; class evidence from McNeill-sensei',
    checked: snapshot.date,
    rights: 'link-only',
    status: 'snapshot',
    notes:
      'Independent language practice. No assessed submission answers or private travel/family details.',
  },
  {
    id: 'timetable',
    title: 'Verified Semester 1 course order',
    type: 'vault-notes',
    reference: '2026-27 Verified Timetable; course fields only',
    author: 'School schedule, curated by Jovan Pahal',
    checked: snapshot.date,
    rights: 'link-only',
    status: 'snapshot',
    notes:
      'P1–P4 order and term span only; no student identifiers or unrelated commitments.',
  },
  {
    id: 'bleecker-site',
    title: 'Bleecker course site',
    type: 'teacher-site',
    url: 'https://sites.google.com/view/ecl-life-sciences-11/home',
    author: 'J. Bleecker',
    checked: snapshot.date,
    rights: 'link-only',
    status: 'checked',
    notes:
      'Bounded index of Home, Calendar, C17, C18, cladograms, vocabulary, Notes and Course pages. Linked resource URLs are indexed; teacher files remain at their original source.',
  },
  {
    id: 'bleecker-calendar',
    title: 'Biology 11 teacher calendar',
    type: 'teacher-calendar',
    url: 'https://calendar.google.com/calendar/embed?src=q87773ofbdnsahhi3vmatr59t0%40group.calendar.google.com&ctz=America%2FVancouver',
    author: 'J. Bleecker',
    checked: snapshot.date,
    rights: 'link-only',
    status: 'checked',
    notes:
      'Live calendar and public iCalendar feed checked. Dates normalized as local all-day dates; end dates are exclusive in source.',
  },
  {
    id: 'bleecker-video',
    title: 'Saved Biology 11 lesson-video playlist',
    type: 'teacher-site',
    url: 'https://tinyurl.com/mp2rdru',
    author: 'J. Bleecker',
    checked: snapshot.date,
    rights: 'link-only',
    status: 'unavailable',
    notes:
      'Saved shortlink returns HTTP 404. No playlist, caption or transcript ingest claimed; replacement link needed.',
  },
  {
    id: 'district-calendar',
    title: 'SD57 school district calendars',
    type: 'reference',
    url: 'https://sd57.bc.ca/district/school-district-calendars/',
    author: 'School District 57',
    checked: snapshot.date,
    rights: 'link-only',
    status: 'checked',
    notes:
      'Published 2026–27 district calendar. Local teacher calendar additionally records Pro-D dates and winter break.',
  },
  {
    id: 'chem-reference',
    title: 'Chemistry reference: electrons and molecular structure',
    type: 'reference',
    url: 'https://openstax.org/books/chemistry-2e/pages/6-4-electronic-structure-of-atoms-electron-configurations',
    author: 'OpenStax',
    checked: snapshot.date,
    rights: 'link-only',
    status: 'checked',
    notes:
      'Factual cross-check; all public explanations/questions are original atlas wording.',
  },
  {
    id: 'physics-reference',
    title: 'Physics reference: motion graphs',
    type: 'reference',
    url: 'https://openstax.org/books/physics/pages/3-2-representing-acceleration-with-equations-and-graphs',
    author: 'OpenStax',
    checked: snapshot.date,
    rights: 'link-only',
    status: 'checked',
    notes: 'Factual cross-check only; no source text or figures mirrored.',
  },
  {
    id: 'life-reference',
    title: 'Biology reference: evolutionary relationships',
    type: 'reference',
    url: 'https://openstax.org/books/biology-2e/pages/20-1-organizing-life-on-earth',
    author: 'OpenStax',
    checked: snapshot.date,
    rights: 'link-only',
    status: 'checked',
    notes: 'Factual cross-check; original teaching and examples.',
  },
  {
    id: 'japanese-reference',
    title: 'Japan Foundation: beginner language and scripts',
    type: 'reference',
    url: 'https://marugoto.jpf.go.jp/en/e-learning/index.html',
    author: 'The Japan Foundation',
    checked: snapshot.date,
    rights: 'link-only',
    status: 'checked',
    notes:
      'Linked authoritative learning resources; no audio mirrored and no random-device pronunciation used.',
  },
  {
    id: 'atlas-original',
    title: 'Original atlas explanations and practice',
    type: 'original',
    author: 'Jovan Pahal / atlas',
    checked: snapshot.date,
    rights: 'original',
    status: 'checked',
    notes:
      'Independent study companions, new examples and deterministic evaluated question families.',
  },
];

type LessonInput = [
  id: string,
  course: string,
  unit: string,
  title: string,
  model: string,
  why: string,
  representation: string,
  example: string,
  steps: string[],
  trap: string,
  prerequisites: string[],
];
const lessonInputs: LessonInput[] = [
  [
    'unit-cancellation',
    'chemistry',
    'measurement',
    'Units that cancel',
    'A conversion changes the way a quantity is written, not the quantity itself. Multiply by an equality written as a fraction equal to one.',
    'Write the unwanted unit in the opposite position in the factor. It then cancels algebraically. The uncancelled unit must be the target before you do any arithmetic.',
    'quantity × target unit / starting unit',
    'Convert 2.4 minutes to seconds.',
    [
      'Start from the true equality 1 min = 60 s.',
      '2.4 min × 60 s / 1 min = 144 s.',
    ],
    'A factor can contain correct numbers but still be upside down. Check units first.',
    [],
  ],
  [
    'powered-units',
    'chemistry',
    'measurement',
    'Powered units & rates',
    'When an area or volume unit changes, the entire conversion factor is squared or cubed. A rate also has a denominator to convert.',
    'A square centimetre has two length dimensions. Each changes by the length factor, so the area changes by the square of that factor. Denominator units cancel in the opposite orientation.',
    '(1 m / 100 cm)² = 1 m² / 10,000 cm²',
    'Convert 2500 cm² to square metres.',
    ['Multiply 2500 cm² by (1 m / 100 cm)².', '2500 / 10,000 = 0.25 m².'],
    'Changing cm² to m² by dividing by 100 loses one dimension.',
    ['unit-cancellation'],
  ],
  [
    'scientific-notation',
    'chemistry',
    'measurement',
    'Scientific notation',
    'Write a number as one coefficient between 1 and 10 multiplied by a power of ten. The exponent records its scale.',
    'Multiplication combines coefficients and adds exponents; division divides coefficients and subtracts exponents. Normalize at the end so the coefficient and exponent remain consistent.',
    'a × 10ⁿ, with 1 ≤ |a| < 10 for nonzero values',
    'Multiply (3 × 10⁴) by (2 × 10⁻²).',
    ['3 × 2 = 6.', '4 + (-2) = 2, so the result is 6 × 10².'],
    'An exponent change must be offset by the coefficient. 60 × 10¹ equals 6 × 10².',
    [],
  ],
  [
    'significant-figures',
    'chemistry',
    'measurement',
    'Significant figures',
    'Reported digits communicate measurement precision. The rounding rule follows the operation you performed.',
    'For multiplication/division, the least precise measurement by significant-digit count limits the result. For addition/subtraction, the least precise decimal place limits the result. Exact counted values do not limit precision.',
    'Multiply/divide: significant figures. Add/subtract: decimal places.',
    'Add 12.31 g and 0.4 g.',
    [
      'The unrounded sum is 12.71 g.',
      'The tenths place is the least precise place: report 12.7 g.',
    ],
    'Do not use the fewest-significant-figures rule for a sum. Avoid rounding intermediate calculations.',
    ['scientific-notation'],
  ],
  [
    'atomic-identity',
    'chemistry',
    'atomic',
    'Atoms, isotopes & ions',
    'Protons identify the element. Neutrons distinguish isotopes. Electron gains or losses make ions without changing the element.',
    'Atomic number Z counts protons; mass number A counts protons plus neutrons. Net ion charge compares proton and electron counts, while nuclear charge still depends only on protons.',
    'neutrons = A − Z; electrons = Z − signed ion charge',
    'An oxygen-18 ion has charge 2−. Count its particles.',
    [
      'Oxygen has Z = 8, so 8 protons.',
      '18 − 8 = 10 neutrons. Charge 2− means 10 electrons.',
    ],
    'Ion charge and nuclear charge are different quantities. An anion has extra electrons, not extra protons.',
    [],
  ],
  [
    'electron-configuration',
    'chemistry',
    'atomic',
    'Electron configurations',
    'Configurations describe how electrons occupy shells and subshells. Count the electrons, fill the low-energy places, then check the total.',
    'Each orbital holds at most two electrons with opposite spins. Equal-energy orbitals fill singly before pairing. Common filling order places 4s before 3d for neutral atoms, but transition-metal cations lose highest-n electrons first.',
    's: 2; p: 6; d: 10; f: 14 electrons per subshell',
    'Write a ground-state configuration for sodium.',
    [
      'Sodium has 11 electrons.',
      '1s² 2s² 2p⁶ 3s¹; core form [Ne] 3s¹. Superscripts sum to 11.',
    ],
    'For Fe²⁺ remove 4s before 3d. Cr and Cu are exceptions: [Ar] 3d⁵ 4s¹ and [Ar] 3d¹⁰ 4s¹.',
    ['atomic-identity'],
  ],
  [
    'valence-electrons',
    'chemistry',
    'atomic',
    'Valence electrons',
    'For main-group atoms, the outer-shell electrons are the ones most directly involved in bonding.',
    'Atoms in the same main-group column share an outer-shell pattern. Reading that pattern from the configuration connects the periodic table to common ions and bonds.',
    'Main-group outer shell: ns and np electrons',
    'How many valence electrons does sulfur have?',
    ['Sulfur ends in 3s² 3p⁴.', '2 + 4 = 6 outer-shell electrons.'],
    'The final written subshell is not always the whole valence shell. Transition metals need additional care.',
    ['electron-configuration'],
  ],
  [
    'periodic-trends',
    'chemistry',
    'bonding',
    'Why periodic trends happen',
    'Radius and attraction follow three levers: nuclear pull, distance from the nucleus and shielding by inner electrons.',
    'Across a period, increasing proton count generally strengthens effective attraction within the same shell and shrinks radius. Down a group, an added shell and more shielding place valence electrons farther away. Ionization energy generally rises when an electron is harder to remove.',
    'Across: radius usually ↓, ionization energy usually ↑. Down: radius usually ↑.',
    'Compare neutral Li and neutral K.',
    [
      'Both are in group 1.',
      'K has more occupied shells, so its outer electron is farther away and its radius is larger.',
    ],
    'Trend arrows are general patterns, not exception-free laws. Explain the competing causes.',
    ['valence-electrons'],
  ],
  [
    'electronegativity',
    'chemistry',
    'bonding',
    'Electronegativity & bond polarity',
    'Electronegativity is an atom’s pull on shared bonding electrons. Unequal pull makes a polar bond.',
    'A shared pair can spend more time near one atom. That end becomes partially negative and the other partially positive. Partial charges describe uneven sharing, not complete electron transfer.',
    'δ+ — δ−; bond dipole points toward the more electronegative atom',
    'Which end of an H—F bond is partially negative?',
    [
      'Fluorine pulls the shared electrons more strongly.',
      'F is δ− and H is δ+.',
    ],
    'A polar bond does not by itself prove a whole molecule is polar; shape determines cancellation.',
    ['periodic-trends'],
  ],
  [
    'bond-types',
    'chemistry',
    'bonding',
    'Where the bonding electrons go',
    'Ionic bonding attracts oppositely charged ions; covalent bonding shares pairs; metals have delocalized electrons.',
    'Electron mobility connects microscopic bonding to properties. A solid ionic lattice holds ions in place, while melted or dissolved ions can carry current. Metallic electrons can move through a solid.',
    'ionic: ions; covalent: shared pairs; metallic: mobile delocalized electrons',
    'Why can molten sodium chloride conduct electricity?',
    ['Melting lets its ions move.', 'Moving charged particles carry current.'],
    'Solid ionic compounds usually cannot conduct, even though they contain charges. Covalent network solids differ from small molecular substances.',
    ['valence-electrons', 'electronegativity'],
  ],
  [
    'intermolecular-forces',
    'chemistry',
    'bonding',
    'Attractions between molecules',
    'Intermolecular forces act between molecules. Dispersion arises from fluctuating charge; hydrogen bonding is a stronger specific attraction in suitable molecules.',
    'All atoms and molecules can develop temporary uneven electron distributions. Polarizability can make dispersion substantial. Hydrogen bonding requires H bonded to N, O or F interacting with an available lone pair; boiling separates molecules rather than breaking all covalent bonds.',
    'H—N/O/F ··· lone pair on N/O/F; dispersion exists in all molecules',
    'When pure water boils, what is mainly being overcome?',
    [
      'Attractions between water molecules are weakened.',
      'The O—H covalent bonds inside each molecule remain intact.',
    ],
    'Do not call every bond containing hydrogen a hydrogen bond. Dispersion is not always negligible.',
    ['bond-types'],
  ],
  [
    'lewis-structures',
    'chemistry',
    'shape',
    'Building Lewis structures',
    'A Lewis structure accounts for valence electrons as bonding pairs and lone pairs. It is a bookkeeping model before it is a shape.',
    'Count all valence electrons, adjust for charge, connect atoms, distribute remaining electrons and check the total. Typical main-group structures aim for octets with hydrogen limited to two; exceptions must be handled explicitly.',
    'Total valence electrons = atom contributions − signed charge',
    'Build a Lewis model for H₂O.',
    [
      'O supplies 6 electrons and two H supply 2: total 8.',
      'Two O—H single bonds use 4; two lone pairs on O use the remaining 4.',
    ],
    'Do not silently create electrons to fill octets. The total electron budget must balance.',
    ['valence-electrons', 'bond-types'],
  ],
  [
    'electron-groups',
    'chemistry',
    'shape',
    'Electron groups: the missing bridge',
    'For VSEPR, count regions of electron density around a central atom. A single, double or triple bond counts as one group; a lone pair counts as one.',
    'VSEPR models repulsion between regions rather than counting individual lines or electrons. A multiple bond occupies one direction from the central atom, even though it contains more than one pair.',
    'electron groups = bonded-atom directions + lone pairs on the central atom',
    'Count electron groups around carbon in CO₂.',
    [
      'Its Lewis structure has two double bonds from C.',
      'Each double bond is one group: 2 groups and no central lone pairs.',
    ],
    'Counting four bond lines in CO₂ as four groups predicts the wrong geometry.',
    ['lewis-structures'],
  ],
  [
    'vsepr',
    'chemistry',
    'shape',
    'Shape from electron groups',
    'Electron groups spread out. Molecular shape names the positions of atoms, while electron geometry also counts lone pairs.',
    'Two groups arrange linearly; three arrange trigonal-planar; four arrange tetrahedrally. Lone pairs occupy regions too, so removing them from the shape name changes the molecular shape. In water, four groups give bent atom positions.',
    '2: linear 180°. 3: trigonal planar 120°. 4: tetrahedral ≈109.5° before lone-pair effects.',
    'Predict the molecular shape of NH₃.',
    [
      'N has three bonded H and one lone pair: four groups.',
      'Electron geometry is tetrahedral; molecular shape is trigonal pyramidal.',
    ],
    'Electron geometry and molecular shape match only when there are no central lone pairs.',
    ['electron-groups'],
  ],
  [
    'algebra-rearrangement',
    'physics',
    'basic-skills',
    'Rearrange before substituting',
    'Keep both sides equal while undoing operations around the unknown. Rearrange symbolically, then insert quantities with units.',
    'Inverse operations preserve equality. A symbolic result is easier to check dimensionally and keeps a calculator expression from hiding a mistaken denominator or sign.',
    'v = d/t → t = d/v',
    'Solve F = ma for a.',
    ['Divide both sides by m (for nonzero m).', 'a = F/m.'],
    'Moving a symbol is shorthand for an operation on both sides. Undoing a square may give two roots until physics selects one.',
    [],
  ],
  [
    'physics-units',
    'physics',
    'basic-skills',
    'SI units & conversion checks',
    'A quantity contains a number and a unit. Unit algebra can expose a wrong equation before arithmetic does.',
    'Equalities make conversion factors. Speed needs length per time, acceleration length per time squared. If a result has the wrong dimension, a correct numerical calculation cannot rescue it.',
    '(m/s) / s = m/s²',
    'Convert 0.75 km to metres.',
    ['1 km = 1000 m.', '0.75 km × 1000 m / 1 km = 750 m.'],
    'Convert all relevant quantities to compatible units before using an equation.',
    [],
  ],
  [
    'graph-slope',
    'physics',
    'basic-skills',
    'Slope is a ratio of changes',
    'Slope compares vertical change with horizontal change. Read axis quantities and units before interpreting it.',
    'Two points determine rise over run for a straight segment. Their absolute heights are not the slope. A best-fit line uses representative points on the line, not necessarily two raw data points.',
    'slope = Δy / Δx',
    'A line goes from (2 s, 5 m) to (6 s, 17 m). Find its slope.',
    ['Δy = 12 m and Δx = 4 s.', 'Slope = 3 m/s.'],
    'Using y/x instead of Δy/Δx fails when the graph has a nonzero intercept.',
    ['physics-units'],
  ],
  [
    'vector-sign',
    'physics',
    'kinematics',
    'Direction before signs',
    'A scalar has magnitude. A vector has magnitude and direction. In one dimension, a chosen positive axis represents direction with a sign.',
    'The coordinate choice is a convention. Reversing the positive axis reverses directional signs consistently without changing the physical event. A negative velocity means one direction, not automatically slowing down.',
    '+ east, − west (one possible convention)',
    'Choose east positive. A cart travels west at 3 m/s. Write velocity.',
    ['West is opposite the positive axis.', 'v = −3 m/s.'],
    'Speed is nonnegative magnitude; velocity carries direction. State your axis choice.',
    [],
  ],
  [
    'displacement',
    'physics',
    'kinematics',
    'Distance & displacement',
    'Distance adds the path travelled. Displacement compares only final and initial positions.',
    'Backtracking adds distance but can cancel displacement. Average speed uses distance; average velocity uses displacement. They answer different questions even for the same trip.',
    'Δx = x_f − x_i',
    'Walk 8 m east then 3 m west. Find distance and displacement.',
    [
      'Distance = 8 + 3 = 11 m.',
      'With east positive, displacement = +8 − 3 = +5 m.',
    ],
    'Returning to your start gives zero displacement, not zero distance.',
    ['vector-sign'],
  ],
  [
    'velocity',
    'physics',
    'kinematics',
    'Velocity as position change',
    'Average velocity is displacement divided by elapsed time. On a position-time graph, velocity is slope.',
    'Position change per second is a signed rate. The same displacement over less time means greater velocity magnitude. A curved position graph has changing slope and therefore changing velocity.',
    'v_avg = Δx/Δt',
    'A cart moves from x = 2 m to x = 14 m in 4 s.',
    ['Displacement is 14 − 2 = +12 m.', 'Average velocity = +12/4 = +3 m/s.'],
    'Position is the graph height. Velocity is its slope; a high position does not mean high speed.',
    ['displacement', 'graph-slope'],
  ],
  [
    'acceleration',
    'physics',
    'kinematics',
    'Acceleration & speed changes',
    'Acceleration is velocity change per time. Velocity and acceleration with the same sign increase speed; opposite signs decrease it.',
    'A change in direction is a change in velocity, even when speed is unchanged. In one dimension, compare signs before calling acceleration speeding up or slowing down.',
    'a_avg = (v_f − v_i)/Δt',
    'A car changes from −12 m/s to −4 m/s in 4 s.',
    [
      'Change in velocity = −4 − (−12) = +8 m/s.',
      'Acceleration = +2 m/s². Speed decreased from 12 to 4 m/s.',
    ],
    'Positive acceleration can slow an object moving in the negative direction.',
    ['velocity'],
  ],
  [
    'motion-graphs',
    'physics',
    'kinematics',
    'Slope & area tell different stories',
    'On position-time graphs slope is velocity. On velocity-time graphs slope is acceleration and signed area is displacement.',
    'Area accumulates rate over time: (metres/second) × seconds gives metres. A horizontal velocity graph can have nonzero area despite zero slope. Area below zero contributes negative displacement.',
    'x–t slope → v; v–t slope → a; v–t area → Δx',
    'A velocity graph stays at −2 m/s for 5 s.',
    [
      'Slope is zero, so acceleration is zero.',
      'Signed rectangular area = −2 × 5 = −10 m displacement.',
    ],
    'A horizontal line on a velocity graph does not mean rest unless it lies at zero velocity.',
    ['velocity', 'acceleration'],
  ],
  [
    'kinematic-equations',
    'physics',
    'kinematics',
    'Choose the equation from the unknown',
    'For constant acceleration, list knowns and the requested unknown. Choose a relationship that excludes the quantity you lack.',
    'The standard equations are consistent ways to integrate a constant rate of velocity change. Their constant-acceleration condition matters. The formula sheet supplies the relations, while you supply signs, units and meaning.',
    'v_f = v_i + at; Δx = v_i t + ½at²; v_f² = v_i² + 2aΔx',
    'A cart starts at 2 m/s and accelerates at 3 m/s² for 4 s. Find final velocity.',
    [
      'Need final velocity, with initial velocity, acceleration and time known.',
      'v_f = 2 + 3×4 = 14 m/s.',
    ],
    'Do not substitute numbers before deciding their directional signs. These equations assume constant acceleration.',
    ['acceleration', 'algebra-rearrangement'],
  ],
  [
    'free-fall',
    'physics',
    'kinematics',
    'Free fall is constant acceleration',
    'Ignoring air resistance near Earth, gravity accelerates motion downward at about 9.8 m/s², even at the top of a throw.',
    'A zero instantaneous velocity does not remove the gravitational acceleration. With up chosen positive, a is negative during both upward and downward motion. This is ordinary constant-acceleration kinematics.',
    'Up positive: a ≈ −9.8 m/s²',
    'At the peak of a vertically thrown ball, what are v and a?',
    [
      'The ball has v = 0 at that instant.',
      'Acceleration remains approximately −9.8 m/s² if up is positive.',
    ],
    'The top is a momentary stop, not a moment without gravity.',
    ['vector-sign', 'kinematic-equations'],
  ],
  [
    'bio-roots',
    'life-sciences',
    'classification',
    'Decode biological vocabulary',
    'Break a term into meaningful roots, then check the scientific definition. A root is a clue rather than a complete answer.',
    'Reusable roots compress a large vocabulary: bio relates to life, phylo to groups/lineage and morph to form. Context controls the full meaning, so retrieval needs a precise definition after the clue.',
    'bio = life; morph = form; phylo = lineage/group',
    'Use roots to approach morphology.',
    [
      'Morph suggests form or shape.',
      'Morphology studies the form/structure of organisms.',
    ],
    'A plausible root-based guess must still be checked against the actual term definition.',
    [],
  ],
  [
    'classification',
    'life-sciences',
    'classification',
    'Classification hierarchy',
    'Taxonomy organizes and names organisms in nested groups. More specific ranks sit inside broader ones.',
    'A hierarchy lets a name carry increasingly precise information. In the traditional sequence, a genus contains species and is itself contained within a family. The course uses seven Linnaean ranks below domain.',
    'Kingdom → Phylum → Class → Order → Family → Genus → Species',
    'Which is broader: family or genus?',
    [
      'Find both in the hierarchy.',
      'Family contains genera, so family is broader.',
    ],
    'Read the requested direction: broadest-to-narrowest is not the reverse.',
    ['bio-roots'],
  ],
  [
    'binomial-names',
    'life-sciences',
    'classification',
    'Two-part scientific names',
    'A species name combines genus and specific epithet. Capitalize genus, lowercase the epithet, and italicize both when typed.',
    'Shared naming avoids common-name ambiguity across regions and languages. The specific epithet alone is not the full species name; it must be paired with its genus.',
    'Genus species, for example Panthera leo',
    'Which part of Panthera leo is the genus?',
    [
      'The first part is genus.',
      'Panthera is capitalized; leo is the lowercase specific epithet.',
    ],
    'Call the naming system binomial nomenclature. The second word alone is incomplete.',
    ['classification'],
  ],
  [
    'phylogeny',
    'life-sciences',
    'classification',
    'Relationships from ancestry',
    'Phylogeny describes evolutionary history and relationships. Similar appearance is evidence to investigate, not proof of a recent common ancestor.',
    'Traits can be inherited, lost or independently evolved. Combining morphological and molecular evidence helps distinguish shared history from similar solutions to similar environments.',
    'Hypothesized common ancestor → descendant lineages',
    'A shark and dolphin both have streamlined bodies. Does this alone establish close ancestry?',
    [
      'Similar environments can favour similar body shapes.',
      'Use additional inherited and molecular evidence before inferring close ancestry.',
    ],
    'Overall appearance can hide convergence. Relatedness follows ancestry.',
    ['classification'],
  ],
  [
    'derived-traits',
    'life-sciences',
    'classification',
    'Shared derived traits',
    'A shared derived trait is an evolutionary innovation inherited by descendants of the ancestor in which it appeared.',
    'A trait helps define a branch relative to the comparison group. A clade includes an ancestor and all its descendants. Derived is relative to the ancestral condition being used, not a synonym for advanced.',
    'Trait appears at a branch → descendants inherit it, with possible later loss',
    'An ancestor gains a new inherited structure. Which descendants initially share it?',
    [
      'Trace descendants downstream from that ancestor.',
      'The inherited change marks that branch, subject to later modifications or loss.',
    ],
    'An acquired change during one individual’s life is not automatically an inherited derived character.',
    ['phylogeny'],
  ],
  [
    'cladograms',
    'life-sciences',
    'classification',
    'Read the common ancestor',
    'The most recent shared branch point determines closeness on a cladogram. Tip spacing and left-to-right order do not.',
    'Rotating branches around the same node leaves ancestry unchanged. A node-based reading follows the path from each tip backward until those paths meet.',
    'Find each tip’s path back to the shared node',
    'A and B share a recent node; C joins deeper in the tree. Which pair is closest?',
    [
      'A and B meet at the more recent node.',
      'They remain closest if the diagram’s tips are rearranged around that node.',
    ],
    'Do not count horizontal distance between names as evolutionary distance.',
    ['derived-traits'],
  ],
  [
    'molecular-evidence',
    'life-sciences',
    'classification',
    'DNA evidence & molecular clocks',
    'Inherited sequence similarities help reconstruct relationships. A molecular clock estimates divergence time using calibrated rates of sequence change.',
    'Changes accumulate over generations. Comparing suitable sequences can test ancestry hypotheses, but rates vary and require calibration; a raw difference count is not an exact calendar.',
    'sequence differences + rate calibration → estimated divergence time',
    'Two lineages differ at a studied gene. What extra information is needed to estimate time?',
    [
      'Estimate a suitable substitution rate and calibration.',
      'Interpret the estimate alongside other evidence and uncertainty.',
    ],
    'A molecular clock is not simply the fact that mutations are passed down.',
    ['phylogeny'],
  ],
  [
    'domains-kingdoms',
    'life-sciences',
    'classification',
    'Domains & the course’s six kingdoms',
    'The three domains are Bacteria, Archaea and Eukarya. This course pairs them with a traditional six-kingdom model.',
    'Bacteria maps to Eubacteria and Archaea to Archaebacteria in this classroom model. Eukarya includes Protista, Fungi, Plantae and Animalia. Modern classifications can use different groupings, so this is a local teaching convention.',
    'Domain Archaea ≠ kingdom Archaebacteria',
    'Place fungi into a domain and kingdom.',
    ['Fungal cells are eukaryotic.', 'Domain Eukarya; kingdom Fungi.'],
    'Archaea is the domain name. Not all archaea live in extreme environments.',
    ['classification'],
  ],
  [
    'fossilization',
    'life-sciences',
    'origins',
    'From remains to fossil record',
    'Rapid burial and preservation can leave remains or traces in rock. The fossil record is evidence of past life with large preservation gaps.',
    'Sediment can bury remains and later compact/cement into sedimentary rock. Heat and melting usually destroy delicate evidence, which helps explain why fossils are most common in sedimentary rather than igneous rock.',
    'burial → preservation → sediment becomes rock → later exposure',
    'Why is a shell buried by mud more likely to fossilize than one left exposed?',
    [
      'Burial reduces disturbance and destruction.',
      'Preserved remains may persist as sediment becomes rock.',
    ],
    'Most organisms never fossilize. Absence from the record alone is weak evidence of absence.',
    [],
  ],
  [
    'relative-dating',
    'life-sciences',
    'origins',
    'Relative dating & index fossils',
    'Relative dating orders events as older or younger. In undisturbed sedimentary layers, lower layers formed before higher ones.',
    'Superposition gives an order, not a numerical age. A widespread, recognizable species that existed briefly can help correlate layers at different sites. Disturbance and reworking must be considered.',
    'undisturbed lower layer → older; matching useful index fossils → correlate layers',
    'Layer A lies below B in an undisturbed sequence. Which is older?',
    [
      'Apply superposition.',
      'A is older; the layers alone do not say how many years older.',
    ],
    'Folding or overturning can invalidate a simple lower-equals-older reading.',
    ['fossilization'],
  ],
  [
    'half-life',
    'life-sciences',
    'origins',
    'Radiometric dating & half-life',
    'A half-life is the time for half the parent radioactive atoms to decay. Repeated halvings connect remaining fraction to age.',
    'A closed system with suitable known initial conditions lets isotope measurements estimate elapsed time. 100%, 50%, 25% and 12.5% represent zero, one, two and three half-lives. Fossils may be dated through associated suitable rocks rather than directly.',
    'remaining parent fraction = (½)ⁿ; age = n × half-life',
    'A model sample retains 25% parent; half-life is 800 years.',
    [
      '25% means two halvings.',
      '2 × 800 = 1600 years, under the stated model assumptions.',
    ],
    'Half of the remainder decays each interval, not the same fixed fraction of the starting amount.',
    ['relative-dating'],
  ],
  [
    'geologic-time',
    'life-sciences',
    'origins',
    'Eras, periods & Earth’s age',
    'Geologic time organizes Earth’s history. Eras contain periods; Earth is about 4.6 billion years old.',
    'Radiometric evidence from old Earth and solar-system materials supports the age estimate. The Paleozoic, Mesozoic and Cenozoic eras follow one another; the Cenozoic begins around the end-Cretaceous extinction about 66 million years ago.',
    'Paleozoic → Mesozoic → Cenozoic; era > period',
    'Is the Jurassic an era or a period?',
    [
      'Jurassic is within the Mesozoic.',
      'It is a period, a smaller division of an era.',
    ],
    'Do not confuse Earth’s age with the much more recent start of the Cenozoic.',
    ['half-life'],
  ],
  [
    'early-earth',
    'life-sciences',
    'origins',
    'Early Earth & chemical origins',
    'Early Earth differed from today. Chemical-origin experiments explore how nonliving chemistry can produce building blocks; they do not demonstrate the creation of life.',
    'The Miller–Urey experiment supplied energy to a particular gas/water mixture and produced organic molecules including amino acids. The exact ancient atmosphere remains a scientific question. Proteinoid microspheres illustrate cell-like compartments without being living cells.',
    'simple chemicals + energy → some organic building blocks',
    'What claim is supported when an experiment produces amino acids without organisms?',
    [
      'Some organic building blocks can form through nonliving chemistry.',
      'This does not show that a complete living cell was created.',
    ],
    'Organic does not mean alive. Microspheres and amino acids are not complete organisms.',
    ['geologic-time'],
  ],
  [
    'endosymbiosis',
    'life-sciences',
    'origins',
    'Endosymbiotic theory',
    'Mitochondria and chloroplasts descend from bacteria that became long-term partners inside ancestral cells.',
    'These organelles have features consistent with bacterial ancestry, including their own DNA and division by fission. Engulfment plus a stable mutual relationship explains how distinct cells became organelles over evolutionary time.',
    'engulfed bacteria → persistent symbiosis → organelles',
    'Which organelle has an origin linked to photosynthetic bacteria?',
    [
      'Photosynthesis is performed by chloroplasts.',
      'Chloroplast ancestry links to photosynthetic bacteria.',
    ],
    'The theory concerns specific organelles, not a claim that every cell structure was an engulfed bacterium.',
    ['early-earth'],
  ],
  [
    'evolution-patterns',
    'life-sciences',
    'origins',
    'Patterns & pace of evolution',
    'Evolution can show extinction, diversification, convergence or reciprocal change. Pattern names describe different kinds of evidence.',
    'Adaptive radiation diversifies descendants from a common ancestor. Convergence produces similar traits independently. Coevolution involves reciprocal selection between interacting lineages. Gradualism and punctuated equilibrium describe different patterns of evolutionary change through time.',
    'radiation: one lineage → many niches; convergence: separate lineages → similar solutions',
    'Unrelated lineages independently evolve similar structures. Name the pattern.',
    [
      'Independent similarity points to convergence.',
      'It does not by itself indicate a newly shared ancestor.',
    ],
    'Punctuated equilibrium includes long relative stasis with comparatively rapid change; it is not instantaneous magic. Hox genes affect developmental patterning.',
    ['phylogeny', 'geologic-time'],
  ],
  [
    'hiragana',
    'japanese',
    'writing',
    'Hiragana · ひらがな',
    'Hiragana is a phonetic kana script used for grammatical endings, particles and many Japanese words.',
    'Kana encode sound units rather than each character carrying a lexical meaning. The 46 basic forms underpin later combinations and marked forms. Print and handwriting can differ, so stroke accuracy needs practice with a trusted model.',
    'あ い う え お → a i u e o',
    'Identify the script in あさ.',
    [
      'あ and さ are hiragana.',
      'Read the kana sound units before attaching a word meaning.',
    ],
    'Font recognition does not demonstrate handwriting stroke order. The app checks typed production, not pen strokes.',
    [],
  ],
  [
    'katakana',
    'japanese',
    'writing',
    'Katakana · カタカナ',
    'Katakana is a phonetic kana script frequently used for loanwords, foreign names, emphasis and sound effects.',
    'Hiragana and katakana can encode the same sound units with different written forms. Choosing a script depends on usage rather than a completely separate pronunciation system.',
    'ア イ ウ エ オ → a i u e o',
    'What script appears in カメラ?',
    [
      'These characters are katakana.',
      'Katakana is common for loanwords such as kamera.',
    ],
    'Katakana is not exclusively for foreign words; it also has other conventional uses.',
    ['hiragana'],
  ],
  [
    'japanese-scripts',
    'japanese',
    'writing',
    'Scripts work together',
    'Japanese uses kanji, hiragana and katakana together. Rōmaji uses Latin letters; Arabic numerals are ordinary digits.',
    'Kanji commonly supply meaning-bearing word stems while kana provide phonetic forms and grammatical endings. Rōmaji is a representation aid, not a substitute for learning kana. Arabic numerals commonly appear in dates and quantities.',
    '日本 / にほん / nihon: related representations of Japan',
    'How does kanji differ from kana at a beginner level?',
    [
      'Kana principally encode sound units.',
      'Kanji commonly connect written characters with meanings and readings.',
    ],
    'Rōmaji is not only for tourists. A kanji can have more than one reading.',
    ['hiragana', 'katakana'],
  ],
  [
    'mora',
    'japanese',
    'writing',
    'Sound units & long sounds',
    'Japanese rhythm is organized around morae. A long vowel or small っ changes timing and can distinguish words.',
    'A basic kana commonly carries one timing unit; combinations such as きゃ form one mora, while a long vowel adds another. Listening and handwriting need trusted instruction beyond a typed quiz.',
    'あ・い・う・え・お; きゃ = one mora',
    'Does a long vowel add timing compared with a short vowel?',
    [
      'Yes: its extra duration adds a mora.',
      'Keep long sounds distinct when reading and speaking.',
    ],
    'Do not flatten a long vowel into a short one. This app does not claim to grade pronunciation.',
    ['hiragana'],
  ],
];

const sourceFor = (course: string) =>
  course === 'life-sciences'
    ? ['vault-life', 'life-reference']
    : course === 'japanese'
      ? ['vault-japanese', 'japanese-reference']
      : course === 'chemistry'
        ? ['vault-chemistry', 'chem-reference']
        : ['vault-physics', 'physics-reference'];
export const concepts: Concept[] = lessonInputs.map(
  ([
    id,
    course,
    unit,
    title,
    model,
    why,
    representation,
    prompt,
    steps,
    trap,
    prerequisites,
  ]) => ({
    id,
    course,
    unit,
    title,
    kind: 'concept',
    model,
    why,
    representation,
    example: { prompt, steps },
    trap,
    prerequisites,
    depth: 'core',
    memorize:
      course === 'japanese'
        ? 'Retrieve the written forms and their usage.'
        : 'Retrieve the meanings of the terms and the conditions where the model applies.',
    derive:
      course === 'japanese'
        ? 'Use the situation to choose an appropriate form.'
        : 'Rebuild the result from the model, with units or evidence.',
    reference:
      course === 'physics'
        ? 'The current teacher formula sheet is provided on assessments. Know how to use it.'
        : course === 'chemistry'
          ? 'A clean data booklet is provided. Check which tables it contains; your annotations are not supplied.'
          : 'Use teacher sources to verify local terminology and assessment boundaries.',
    review: [model, trap],
    deeper:
      course === 'japanese'
        ? 'Continue with the linked Japan Foundation resources for audio and writing models. Typed checks cannot assess pronunciation or handwriting.'
        : 'The model has a domain of validity. Explain its assumptions before using it in a changed context, then compare your prediction with evidence.',
    aliases: [],
    annotations: [{ term: title.split(' ')[0], definition: model }],
    sources: [...sourceFor(course), 'atlas-original'],
    status: 'publishable',
  }),
);
const formulaMap: Record<string, string> = {
  'unit-cancellation':
    '2.4\\,\\mathrm{min}\\times\\frac{60\\,\\mathrm{s}}{1\\,\\mathrm{min}}=144\\,\\mathrm{s}',
  'powered-units':
    '\\left(\\frac{1\\,\\mathrm{m}}{100\\,\\mathrm{cm}}\\right)^2',
  'scientific-notation': '(3\\times10^4)(2\\times10^{-2})=6\\times10^2',
  'graph-slope': 'm=\\frac{\\Delta y}{\\Delta x}',
  velocity: 'v_{\\mathrm{avg}}=\\frac{\\Delta x}{\\Delta t}',
  acceleration: 'a=\\frac{v_f-v_i}{\\Delta t}',
  'kinematic-equations': '\\Delta x=v_i t+\\frac12 a t^2',
  'half-life': '\\frac{N}{N_0}=\\left(\\frac12\\right)^n',
};
for (const c of concepts) if (formulaMap[c.id]) c.formula = formulaMap[c.id];

// Each phrase is a separate stable node; semantic connections carry usage, not merely backlinks.
const vocabulary: [string, string, string, string, string][] = [
  ['nihon', 'にほん', 'nihon', 'Japan', 'Name the country Japan.'],
  [
    'hai',
    'はい',
    'hai',
    'yes',
    'Give a basic affirmative response. Context can also make this an acknowledgement.',
  ],
  ['iie', 'いいえ', 'iie', 'no', 'Give a basic negative response.'],
  [
    'ohayou',
    'おはようございます',
    'ohayou gozaimasu',
    'good morning',
    'Greet your teacher politely in the morning.',
  ],
  [
    'konnichiwa',
    'こんにちは',
    'konnichiwa',
    'hello / good afternoon',
    'Greet someone during the day. The final は is pronounced wa here.',
  ],
  [
    'konbanwa',
    'こんばんは',
    'konbanwa',
    'good evening',
    'Greet someone in the evening. The final は is pronounced wa here.',
  ],
  [
    'oyasumi',
    'おやすみなさい',
    'oyasuminasai',
    'good night',
    'Say good night as someone goes to bed.',
  ],
  [
    'jaa-mata',
    'じゃあまたね',
    'jaa mata ne',
    'see you later',
    'Say a casual goodbye when expecting to see someone again.',
  ],
  [
    'sayounara',
    'さようなら',
    'sayounara',
    'goodbye',
    'Use the basic goodbye expression from the class list.',
  ],
  [
    'hajimemashite',
    'はじめまして',
    'hajimemashite',
    'nice to meet you',
    'Open a greeting when meeting someone for the first time.',
  ],
  [
    'yoroshiku',
    'よろしく',
    'yoroshiku',
    'please treat me well',
    'Use the class-list expression accompanying a first introduction; its meaning depends on context.',
  ],
  [
    'sumimasen',
    'すみません',
    'sumimasen',
    'excuse me / sorry',
    'Politely get attention or apologize; the situation determines the sense.',
  ],
  [
    'gomennasai',
    'ごめんなさい',
    'gomennasai',
    'sorry',
    'Apologize for something you did.',
  ],
  [
    'onegaishimasu',
    'おねがいします',
    'onegaishimasu',
    'please',
    'Make a polite request rather than translating every English please identically.',
  ],
  [
    'arigatou',
    'ありがとうございます',
    'arigatou gozaimasu',
    'thank you',
    'Thank someone politely.',
  ],
  [
    'douitashimashite',
    'どういたしまして',
    'dou itashimashite',
    'you are welcome',
    'Respond to someone thanking you with the class-list phrase.',
  ],
  [
    'sensei',
    'せんせい',
    'sensei',
    'teacher',
    'Use the title for a teacher in the current beginner vocabulary.',
  ],
  [
    'watashi',
    'わたし',
    'watashi',
    'I / me',
    'Use the current beginner word for yourself; Japanese often omits obvious subjects.',
  ],
];
for (const [id, kana, romaji, meaning, situation] of vocabulary)
  concepts.push({
    id: `jp-${id}`,
    course: 'japanese',
    unit: 'greetings',
    title: kana,
    kind: 'vocabulary',
    model: `${kana} (${romaji}) means ${meaning} in this beginner context. ${situation}`,
    why: `A phrase connects a written form with a social situation. Retrieve ${kana} from the situation, rather than recognizing it only when it appears on a list.`,
    representation: `${kana} · ${romaji} · ${meaning}`,
    example: {
      prompt: situation,
      steps: [
        `Choose ${kana}.`,
        `Meaning here: ${meaning}. Practise saying it with a trusted teacher/audio model.`,
      ],
    },
    trap: ['sumimasen', 'gomennasai'].includes(id)
      ? 'Apologizing and getting attention overlap for すみません, but ごめんなさい is principally an apology. Learn each situation before practising the contrast.'
      : 'Translate the situation, not only the English word. Register and context matter.',
    prerequisites: ['hiragana'],
    depth: 'core',
    memorize: `Retrieve ${kana} and its current meaning.`,
    derive: 'Choose the form from context and politeness.',
    reference:
      'The current handout establishes this 18-item scope; the next quiz date is unconfirmed.',
    review: [situation, `${kana} → ${meaning}`],
    deeper:
      'Later sentence patterns and register choices will add detail. No listening or handwriting score is inferred from typed practice.',
    aliases: [romaji, meaning],
    annotations: [{ term: kana, definition: meaning }],
    sources: ['vault-japanese', 'japanese-reference', 'atlas-original'],
    status: 'publishable',
  });

export const coverageItems: CoverageItem[] = concepts.map((c) => ({
  id: `cover-${c.id}`,
  course: c.course,
  unit: c.unit,
  concept: c.id,
  title: c.title,
  required: c.depth === 'core',
  type: c.kind === 'vocabulary' ? 'term' : 'concept',
  sources: c.sources,
}));
export const edges: Edge[] = concepts.flatMap((c) =>
  c.prerequisites.map((p) => ({
    from: c.id,
    to: p,
    type: 'requires' as const,
    reason: `${c.title} builds on ${concepts.find((x) => x.id === p)?.title}.`,
  })),
);
edges.push(
  {
    from: 'jp-sumimasen',
    to: 'jp-gomennasai',
    type: 'contrasts-with',
    reason:
      'Apology overlaps; polite attention-getting is a distinct use of すみません.',
  },
  {
    from: 'katakana',
    to: 'hiragana',
    type: 'pronounced-as',
    reason:
      'Parallel basic kana represent the same morae in different scripts.',
  },
  {
    from: 'molecular-evidence',
    to: 'cladograms',
    type: 'used-in',
    reason:
      'Sequence comparisons help test evolutionary relationship hypotheses.',
  },
  {
    from: 'unit-cancellation',
    to: 'physics-units',
    type: 'used-in',
    reason:
      'The same dimensional reasoning works across Chemistry and Physics.',
  },
  {
    from: 'vsepr',
    to: 'electronegativity',
    type: 'explains',
    reason:
      'Molecular shape helps explain whether individual bond dipoles cancel.',
  },
);

type Check = [
  concept: string,
  diagnosticPrompt: string,
  correctChoice: string,
  distractors: string[],
  constructionPrompt: string,
  answers: string[],
  transferPrompt: string,
  transferAnswers: string[],
  explanation: string,
];
const checks: Check[] = [
  [
    'unit-cancellation',
    'Convert minutes to seconds. Which factor cancels minutes?',
    '60 s / 1 min',
    ['1 min / 60 s', '60 min / 1 s'],
    'How many seconds are in 1.5 minutes? Type the number.',
    ['90'],
    'A correct conversion produces minutes squared per second. Is the factor orientation correct? Type yes or no.',
    ['no'],
    'Only a factor with minutes in the denominator cancels the starting minutes.',
  ],
  [
    'powered-units',
    'How many cm² equal 1 m²?',
    '10000',
    ['100', '1000'],
    'Convert 400 cm² to m². Type the number.',
    ['0.04'],
    'Convert 2 m³ to cm³. Type the number.',
    ['2000000', '2e6'],
    'Square or cube the complete length factor: 100² or 100³.',
  ],
  [
    'scientific-notation',
    'Which is normalized scientific notation for 0.00072?',
    '7.2 × 10⁻⁴',
    ['72 × 10⁻³', '7.2 × 10⁴'],
    'Write 63000 using e notation, for example 1.2e3.',
    ['6.3e4', '6.3e+4'],
    'Divide 8e5 by 2e2. Use normalized e notation.',
    ['4e3', '4e+3'],
    'Normalize the coefficient; multiplication adds exponents and division subtracts them.',
  ],
  [
    'significant-figures',
    'Which rule applies when adding measured quantities?',
    'Fewest decimal places',
    ['Fewest significant figures', 'Most digits'],
    'Round 5.67 + 2.1 to the appropriate precision. Type the number.',
    ['7.8'],
    'Multiply measurements 2.40 by 3.0. Give the result with appropriate significant figures.',
    ['7.2'],
    'Addition rounds to a decimal place; multiplication rounds to the fewest significant figures.',
  ],
  [
    'atomic-identity',
    'What changes when an atom becomes an ion?',
    'Electron count',
    ['Proton count', 'Element identity'],
    'Magnesium-26 has Z = 12. How many neutrons?',
    ['14'],
    'An atom has 9 protons and 10 electrons. What signed net charge does it have?',
    ['-1', '1-'],
    'Neutrons = A − Z. Net charge = protons − electrons.',
  ],
  [
    'electron-configuration',
    'Maximum electrons in a p subshell?',
    '6',
    ['2', '10'],
    'Write the core configuration for Mg. Use [Ne] and plain digits.',
    ['[ne] 3s2', '[ne]3s2'],
    'Fe is [Ar] 3d6 4s2. Write Fe2+ in core form with plain digits.',
    ['[ar] 3d6', '[ar]3d6'],
    'Highest principal-level electrons are removed first for this transition-metal cation, so the 4s pair is removed.',
  ],
  [
    'valence-electrons',
    'Which main-group electrons most directly participate in bonds?',
    'Outer-shell electrons',
    ['Only core electrons', 'Only neutrons'],
    'Phosphorus ends 3s2 3p3. How many valence electrons?',
    ['5'],
    'A neutral main-group atom ends 4s2 4p5. How many electrons must it gain to fill that shell?',
    ['1', 'one'],
    'Count both ns and np electrons of the highest principal shell for a main-group atom.',
  ],
  [
    'periodic-trends',
    'What usually happens to radius down a group?',
    'It increases',
    ['It decreases', 'It becomes zero'],
    'Which neutral atom is larger: Na or Li? Type the symbol.',
    ['na'],
    'Which usually has higher first ionization energy: Na or Cl? Type the symbol.',
    ['cl'],
    'Added shells enlarge atoms down a group. Stronger effective attraction generally raises ionization energy across a period.',
  ],
  [
    'electronegativity',
    'The more electronegative end of a polar bond is…',
    'Partially negative',
    ['Partially positive', 'Always a full 2− ion'],
    'In H–Cl, which atom is δ−? Type the symbol.',
    ['cl'],
    'Can equal opposite bond dipoles cancel in a linear molecule? Type yes or no.',
    ['yes'],
    'Unequal sharing polarizes bonds; their directional combination determines molecular polarity.',
  ],
  [
    'bond-types',
    'What carries current in molten ionic compounds?',
    'Moving ions',
    ['Fixed ions', 'Only neutrons'],
    'Which bond model has delocalized electrons throughout a solid? Name the model.',
    ['metallic', 'metallic bonding'],
    'Does solid NaCl normally conduct through freely moving ions? Type yes or no.',
    ['no'],
    'Conduction requires mobile charged particles; ions in the solid lattice cannot flow.',
  ],
  [
    'intermolecular-forces',
    'Which attraction exists in all atoms and molecules?',
    'London dispersion',
    ['Hydrogen bonding', 'Ionic lattice bonding'],
    'Name the force associated with temporary induced dipoles.',
    ['london dispersion', 'dispersion', 'london dispersion forces'],
    'Boiling water primarily overcomes intermolecular attractions or O–H covalent bonds? Type intermolecular or covalent.',
    ['intermolecular'],
    'Hydrogen bonding acts between suitable molecules. Ordinary boiling does not split water into its atoms.',
  ],
  [
    'lewis-structures',
    'How many valence electrons does neutral H2O have?',
    '8',
    ['6', '10'],
    'How many lone pairs are on oxygen in the usual H2O Lewis structure? Type the number.',
    ['2'],
    'NH4+ contains 5 + 4 − 1 valence electrons. How many is that?',
    ['8'],
    'Count an electron budget adjusted for charge before drawing and distributing pairs.',
  ],
  [
    'electron-groups',
    'A double bond counts as how many VSEPR groups?',
    '1',
    ['2', '4'],
    'How many groups surround C in CO2?',
    ['2'],
    'How many groups surround O in water with two bonds and two lone pairs?',
    ['4'],
    'Count bonded directions and lone pairs. A multiple bond remains one region.',
  ],
  [
    'vsepr',
    'Four groups with no central lone pairs give what shape?',
    'Tetrahedral',
    ['Bent', 'Linear'],
    'CO2 has two central groups and no lone pairs. Name its shape.',
    ['linear'],
    'Four groups include two bonds and two lone pairs. Name the molecular shape.',
    ['bent', 'angular'],
    'Molecular shape labels only atoms, while electron geometry includes lone-pair regions.',
  ],
  [
    'algebra-rearrangement',
    'Solve v = d/t for t.',
    't = d/v',
    ['t = v/d', 't = dv'],
    'For F = ma, isolate m. Type a formula such as m=F/a.',
    ['m=f/a', 'm = f/a'],
    'For vf² = vi² + 2ad, isolate a using vf, vi and d. Type a=(vf^2-vi^2)/(2d).',
    ['a=(vf^2-vi^2)/(2d)', 'a=(vf²-vi²)/(2d)'],
    'Subtract the initial-velocity square, then divide the complete difference by 2d.',
  ],
  [
    'physics-units',
    'Acceleration has which SI unit?',
    'm/s²',
    ['m/s', 'm·s'],
    'How many metres equal 1.2 km? Type the number.',
    ['1200'],
    'A velocity in m/s is divided by time in s. Type the resulting unit using ^ for powers.',
    ['m/s^2', 'm/s²', 'm/s2'],
    'Unit algebra mirrors the quantity relationship: acceleration is velocity change per time.',
  ],
  [
    'graph-slope',
    'Slope is…',
    'Change in vertical / change in horizontal',
    ['Vertical value only', 'Always y/x'],
    'A line rises 18 m over 6 s. What is its slope in m/s? Type the number.',
    ['3'],
    'Points (2,7) and (5,13) are on a line. What is its slope?',
    ['2'],
    'Use differences: (13−7)/(5−2), not 13/5.',
  ],
  [
    'vector-sign',
    'A negative velocity always means…',
    'Motion opposite the chosen positive direction',
    ['Slowing down', 'Zero speed'],
    'East is positive. Westward velocity has which sign? Type positive or negative.',
    ['negative', '-'],
    'Velocity is negative and acceleration is negative. Is speed increasing or decreasing?',
    ['increasing'],
    'The sign encodes direction. Matching velocity and acceleration signs increase speed.',
  ],
  [
    'displacement',
    'Which uses only final and initial position?',
    'Displacement',
    ['Distance', 'Total path length'],
    'With east positive, move 9 m east then 4 m west. What is displacement in m? Type the number.',
    ['5', '+5'],
    'Walk 6 m east then 6 m west. What distance was travelled in m? Type the number.',
    ['12'],
    'Distance sums path lengths; displacement can cancel.',
  ],
  [
    'velocity',
    'Slope of a position-time graph represents…',
    'Velocity',
    ['Position', 'Acceleration'],
    'A cart moves 24 m east in 6 s. East is positive. Give average velocity in m/s.',
    ['4', '+4'],
    'A trip returns to its start after 20 s. What is average velocity in m/s?',
    ['0'],
    'Use displacement over time; a round trip has zero displacement despite nonzero distance.',
  ],
  [
    'acceleration',
    'Velocity and acceleration have opposite signs. Speed…',
    'Decreases at that instant',
    ['Increases at that instant', 'Must be zero'],
    'Velocity goes from 2 to 14 m/s in 4 s. Give acceleration in m/s².',
    ['3'],
    'A car moves west at 10 m/s and slows to 4 m/s in 3 s. East is positive. Give acceleration in m/s².',
    ['2', '+2'],
    'Change of signed velocity is (−4)−(−10) = +6 m/s; divide by 3 s.',
  ],
  [
    'motion-graphs',
    'Area under velocity-time represents…',
    'Displacement',
    ['Acceleration', 'Position-time slope'],
    'A velocity-time graph is +3 m/s for 4 s. Find displacement in m.',
    ['12'],
    'Velocity is +2 m/s for 3 s, then −2 m/s for 3 s. Find net displacement in m.',
    ['0'],
    'Add signed areas; the positive and negative areas cancel.',
  ],
  [
    'kinematic-equations',
    'Which equation eliminates time for constant acceleration?',
    'vf² = vi² + 2aΔx',
    ['vf = vi + at', 'Δx = vi t + ½at²'],
    'vi=3 m/s, a=2 m/s², t=5 s. Give vf in m/s.',
    ['13'],
    'A cart accelerates uniformly from rest at 2 m/s² for 3 s. Give displacement in m.',
    ['9'],
    'With constant acceleration, displacement = vi t + ½at². From rest, the first term vanishes.',
  ],
  [
    'free-fall',
    'At the top of a vertical throw, ignoring air resistance…',
    'v = 0; acceleration is downward',
    ['v = 0; a = 0', 'Acceleration is upward'],
    'Up is positive. Write gravitational acceleration near Earth in m/s². Type the number.',
    ['-9.8'],
    'A ball is rising, with up positive. Is gravitational acceleration positive or negative?',
    ['negative'],
    'Gravity points downward throughout the flight; the sign follows your axis.',
  ],
  [
    'bio-roots',
    'The root bio most directly suggests…',
    'Life',
    ['Rock', 'Heat'],
    'What does morph refer to? Type form or shape.',
    ['form', 'shape'],
    'Does a root-based guess replace checking the scientific definition? Type yes or no.',
    ['no'],
    'Roots suggest a meaning; context and the definition establish it.',
  ],
  [
    'classification',
    'Which is the most specific listed rank?',
    'Species',
    ['Kingdom', 'Family'],
    'Which rank comes between family and species?',
    ['genus'],
    'Which is broader: order or class?',
    ['class'],
    'Follow Kingdom–Phylum–Class–Order–Family–Genus–Species in the requested direction.',
  ],
  [
    'binomial-names',
    'Which typed name has correct capitalization?',
    'Panthera leo',
    ['panthera Leo', 'PANTHERA LEO'],
    'Name the two-word naming system.',
    ['binomial nomenclature'],
    'In Canis lupus, which part must be capitalized?',
    ['canis', 'genus'],
    'Capitalize the genus; lowercase the specific epithet; italicize both when typed.',
  ],
  [
    'phylogeny',
    'Phylogeny describes…',
    'Evolutionary history and relationships',
    ['Only body size', 'Individual growth only'],
    'Name the process where unrelated lineages independently develop similar traits.',
    ['convergent evolution', 'convergence'],
    'Does a similar streamlined shape alone prove close ancestry? Type yes or no.',
    ['no'],
    'Independent adaptation can make distantly related organisms similar.',
  ],
  [
    'derived-traits',
    'A clade contains…',
    'An ancestor and all its descendants',
    ['Only visually similar tips', 'Only the youngest species'],
    'A shared derived trait is inherited or acquired during an individual’s life? Type inherited or acquired.',
    ['inherited'],
    'Is derived a synonym for more advanced? Type yes or no.',
    ['no'],
    'Derived describes a change relative to an ancestral state, not progress toward a superior form.',
  ],
  [
    'cladograms',
    'Closeness on a cladogram follows…',
    'Most recent common ancestor',
    ['Tip spacing', 'Alphabetical tip order'],
    'A and B share a newer node than A and C. Which pair is closer? Type A and B or A and C.',
    ['a and b', 'ab', 'a b'],
    'Does rotating descendants around a node change ancestry? Type yes or no.',
    ['no'],
    'The branching topology, rather than drawing orientation, carries the relationship.',
  ],
  [
    'molecular-evidence',
    'A molecular clock needs…',
    'A suitable calibrated rate of sequence change',
    ['Only a common name', 'Only tip spacing'],
    'What does a molecular clock estimate: divergence time or body mass?',
    ['divergence time'],
    'Can mutation rates differ among genes or lineages? Type yes or no.',
    ['yes'],
    'The rate must be estimated and calibrated, so divergence times have uncertainty.',
  ],
  [
    'domains-kingdoms',
    'Which is the domain name?',
    'Archaea',
    ['Archaebacteria', 'Animalia'],
    'Which domain includes animals?',
    ['eukarya'],
    'In this course, the kingdom Eubacteria belongs to which domain?',
    ['bacteria'],
    'The class uses six kingdoms under three domains. Keep the ranks and names distinct.',
  ],
  [
    'fossilization',
    'Most fossils occur in…',
    'Sedimentary rock',
    ['Recently molten lava', 'All rock types equally'],
    'Name the first protective step when sediment covers remains.',
    ['burial', 'rapid burial'],
    'Does an incomplete fossil record imply every past organism was preserved? Type yes or no.',
    ['no'],
    'Burial and preservation are selective; many organisms leave no recoverable fossil.',
  ],
  [
    'relative-dating',
    'In an undisturbed sedimentary stack, lower layers are…',
    'Older',
    ['Younger', 'Always exactly 1 million years old'],
    'Does relative dating assign a numeric age? Type yes or no.',
    ['no'],
    'For an index fossil, is a short or long existence interval more useful? Type short or long.',
    ['short'],
    'A short interval narrows the time window when correlating layers across locations.',
  ],
  [
    'half-life',
    '25% parent remaining represents…',
    'Two half-lives',
    ['One half-life', 'Four half-lives'],
    '12.5% remains, half-life 200 years. Give model age in years.',
    ['600'],
    'After four half-lives, what percentage remains? Type the number.',
    ['6.25'],
    'Each half-life halves what remains: 100, 50, 25, 12.5, 6.25.',
  ],
  [
    'geologic-time',
    'Which time division is larger?',
    'Era',
    ['Period', 'Both always equal'],
    'Name the era after the Mesozoic.',
    ['cenozoic'],
    'Earth is approximately 4.6 million or 4.6 billion years old? Type million or billion.',
    ['billion'],
    'Earth’s age is on a billion-year scale; eras and periods subdivide geological history.',
  ],
  [
    'early-earth',
    'Miller–Urey produced…',
    'Organic building blocks',
    ['A complete living cell', 'Modern animals'],
    'Were proteinoid microspheres living cells? Type yes or no.',
    ['no'],
    'Does making amino acids demonstrate that a whole organism was created? Type yes or no.',
    ['no'],
    'Building blocks and cell-like compartments are evidence about chemistry, not complete living organisms.',
  ],
  [
    'endosymbiosis',
    'Chloroplast ancestry is linked to…',
    'Photosynthetic bacteria',
    ['Animal nuclei', 'Sedimentary grains'],
    'Name the organelle descended from aerobic bacteria that supplies much cellular energy.',
    ['mitochondrion', 'mitochondria'],
    'Do mitochondria have their own DNA? Type yes or no.',
    ['yes'],
    'Organelle DNA and fission are among the evidence supporting bacterial origins.',
  ],
  [
    'evolution-patterns',
    'Independent similar traits in unrelated groups suggest…',
    'Convergence',
    ['Adaptive radiation', 'Extinction'],
    'One ancestral lineage diversifies into many niches. Name the pattern.',
    ['adaptive radiation'],
    'Two interacting species exert reciprocal selection. Name the pattern.',
    ['coevolution', 'co-evolution'],
    'Convergence, adaptive radiation and coevolution describe distinct patterns, not interchangeable labels.',
  ],
  [
    'hiragana',
    'Which is hiragana?',
    'あ',
    ['ア', '日'],
    'Type hiragana for a.',
    ['あ'],
    'Which script is typically used for grammatical endings: hiragana or katakana?',
    ['hiragana', 'ひらがな'],
    'Hiragana supplies phonetic forms and many grammatical endings; typed checks do not assess strokes.',
  ],
  [
    'katakana',
    'Which is katakana?',
    'ア',
    ['あ', '本'],
    'Type katakana for a.',
    ['ア'],
    'Which script is common for loanwords: katakana or hiragana?',
    ['katakana', 'カタカナ'],
    'Katakana often represents loanwords but also has other uses.',
  ],
  [
    'japanese-scripts',
    'Kanji principally connect characters with…',
    'Meanings and readings',
    ['Only Latin letters', 'Only digits'],
    'Name the system that uses Latin letters to represent Japanese.',
    ['romaji', 'rōmaji'],
    'Are Arabic numerals used in Japanese dates and prices? Type yes or no.',
    ['yes'],
    'Japanese combines scripts; Latin romanization and ordinary digits also appear.',
  ],
  [
    'mora',
    'A long vowel adds…',
    'A timing unit',
    ['No duration', 'A silent consonant always'],
    'How many morae are in あい? Type the number.',
    ['2'],
    'How many morae are in きゃ? Type the number.',
    ['1'],
    'Small ゃ combines with き as one mora; a long vowel would add another timing unit.',
  ],
];

export const questions: Question[] = checks.flatMap(
  ([concept, dp, da, distractors, cp, ca, tp, ta, explanation]) => {
    const c = concepts.find((c) => c.id === concept)!;
    return [
      {
        id: `${concept}-diagnostic`,
        course: c.course,
        unit: c.unit,
        concepts: [concept],
        coverage: [`cover-${concept}`],
        level: 'recognition' as const,
        purpose: 'diagnostic' as const,
        format: 'choice' as const,
        archetype: `${concept}-recognition`,
        prompt: dp,
        choices: [da, ...distractors],
        answer: da,
      },
      {
        id: `${concept}-construction`,
        course: c.course,
        unit: c.unit,
        concepts: [concept],
        coverage: [`cover-${concept}`],
        level: 'construction' as const,
        purpose: 'mastery' as const,
        format: 'text' as const,
        archetype: `${concept}-construction`,
        prompt: cp,
        answer: ca,
      },
      {
        id: `${concept}-transfer`,
        course: c.course,
        unit: c.unit,
        concepts: [concept],
        coverage: [`cover-${concept}`],
        level: 'transfer' as const,
        purpose: 'transfer' as const,
        format: 'text' as const,
        archetype: `${concept}-transfer`,
        prompt: tp,
        answer: ta,
      },
    ].map((q) => ({
      ...q,
      explanation,
      hint: c.representation,
      diagnosis: c.prerequisites.at(-1) ?? c.id,
      sources: c.sources,
      status: 'publishable' as const,
    }));
  },
);
for (const [id, template, unitLabel] of [
  ['velocity', 'velocity', 'm/s'],
  ['acceleration', 'acceleration', 'm/s²'],
  ['unit-cancellation', 'conversion', 's'],
  ['half-life', 'half-life', 'years'],
] as const) {
  const q = questions.find((q) => q.id === `${id}-construction`)!;
  q.format = 'numeric';
  q.template = template;
  q.unitLabel = unitLabel;
  q.answer = 0;
}
for (const [id, precision] of [
  ['significant-figures-construction', 'decimal-places'],
  ['significant-figures-transfer', 'significant-figures'],
] as const)
  questions.find((q) => q.id === id)!.precision = precision;
for (const [id, kana, romaji, meaning, situation] of vocabulary) {
  const concept = `jp-${id}`;
  const c = concepts.find((c) => c.id === concept)!;
  const alternate = vocabulary
    .filter(
      (v) =>
        v[0] !== id &&
        !(id === 'sumimasen' && v[0] === 'gomennasai') &&
        !(id === 'gomennasai' && v[0] === 'sumimasen'),
    )
    .slice(0, 2)
    .map((v) => v[3]);
  questions.push(
    {
      id: `${concept}-diagnostic`,
      course: 'japanese',
      unit: 'greetings',
      concepts: [concept],
      coverage: [`cover-${concept}`],
      level: 'recognition',
      purpose: 'diagnostic',
      format: 'choice',
      archetype: `${concept}-recognition`,
      prompt: `Choose the current meaning of ${kana}.`,
      choices: [meaning, ...alternate],
      answer: meaning,
      explanation: c.model,
      hint: romaji,
      diagnosis: 'hiragana',
      sources: c.sources,
      status: 'publishable',
    },
    {
      id: `${concept}-construction`,
      course: 'japanese',
      unit: 'greetings',
      concepts: [concept],
      coverage: [`cover-${concept}`],
      level: 'construction',
      purpose: 'mastery',
      format: 'text',
      archetype: `${concept}-production`,
      prompt: `Type the class-list kana phrase for “${meaning}”.`,
      answer: [kana],
      explanation: `${kana} is the current class-list form. This checks typed recall, not handwriting.`,
      hint: `It starts with ${kana[0]}.`,
      diagnosis: 'hiragana',
      sources: c.sources,
      status: 'publishable',
    },
    {
      id: `${concept}-transfer`,
      course: 'japanese',
      unit: 'greetings',
      concepts: [concept],
      coverage: [`cover-${concept}`],
      level: 'transfer',
      purpose: 'transfer',
      format: 'text',
      archetype: `${concept}-situation`,
      prompt: `${situation} Type the phrase from the current list in kana.`,
      answer: [kana],
      explanation: c.model,
      hint: `Recall its use: ${meaning}.`,
      diagnosis: 'hiragana',
      sources: c.sources,
      status: 'publishable',
    },
  );
}

// Smaller facts and representations stay independently untested until their own
// question appears. Demonstrating a broad concept never covers these by proxy.
const detailChecks: [string, string, string, string, string[], string][] = [
  [
    'gradualism',
    'evolution-patterns',
    'Gradualism',
    'A lineage changes through many small accumulated changes. Name this model of evolutionary pace.',
    ['gradualism'],
    'Gradualism describes accumulated change. It differs from long intervals of relative stasis separated by comparatively rapid change.',
  ],
  [
    'punctuated-equilibrium',
    'evolution-patterns',
    'Punctuated equilibrium',
    'Long relative stasis alternates with geologically comparatively rapid change. Name this model.',
    ['punctuated equilibrium'],
    'Punctuated equilibrium concerns the pattern and pace of change; rapid geological change still involves generations.',
  ],
  [
    'hox-patterning',
    'evolution-patterns',
    'Hox genes and body pattern',
    'Hox genes principally regulate body pattern during development or date sedimentary rocks? Type body pattern or dating.',
    ['body pattern'],
    'Hox genes help specify positional identity during development. They are not a radiometric clock.',
  ],
  [
    'microspheres',
    'early-earth',
    'Proteinoid microspheres are not living cells',
    'Does a cell-like proteinoid microsphere alone demonstrate a complete living cell? Type yes or no.',
    ['no'],
    'A compartment-like structure is one relevant property. It does not establish the coordinated processes of a living cell.',
  ],
  [
    'miller-claim',
    'early-earth',
    'What Miller–Urey actually demonstrated',
    'The Miller–Urey setup produced some organic building blocks or complete organisms? Type building blocks or organisms.',
    ['building blocks', 'organic building blocks'],
    'Producing amino acids under model conditions supports a chemical pathway, not the claim that the experiment made living organisms.',
  ],
  [
    'mineral-replacement',
    'fossilization',
    'Mineral replacement',
    'Minerals gradually replace original remains while preserving structure. Name the process.',
    ['mineral replacement', 'replacement', 'permineralization and replacement'],
    'Mineral replacement can preserve structural evidence. It is not identical to a trace left by an organism; permineralization fills pore spaces.',
  ],
  [
    'sedimentary-rock',
    'relative-dating',
    'Fossils and sedimentary rock',
    'Common preserved fossils are usually associated with sedimentary or molten igneous rock? Type sedimentary or igneous.',
    ['sedimentary'],
    'Burial in sediment can preserve remains. High heat during melting generally destroys biological structures.',
  ],
  [
    'extinction',
    'evolution-patterns',
    'Extinction versus radiation',
    'The disappearance of every living member of a species is called what?',
    ['extinction'],
    'Extinction removes a lineage; adaptive radiation diversifies descendants into ecological opportunities.',
  ],
  [
    'clock-calibration',
    'molecular-evidence',
    'Molecular-clock calibration',
    'A sequence difference count alone gives an exact divergence date. Type true or false.',
    ['false'],
    'Estimating divergence time also requires a suitable calibrated rate and uncertainty. Rates can differ among genes and lineages.',
  ],
  [
    'eukaryotic-nucleus',
    'domains-kingdoms',
    'A eukaryotic cell has a nucleus',
    'Bacteria lack a membrane-bound nucleus. Do eukaryotic cells have one? Type yes or no.',
    ['yes'],
    'A membrane-bound nucleus is a defining eukaryotic feature. Bacteria and archaea are prokaryotic domains.',
  ],
  [
    'binomial-format',
    'binomial-names',
    'Scientific-name writing convention',
    'For Panthera leo, capitalize both words or only the genus? Type both or genus.',
    ['genus'],
    'Capitalize Panthera, lowercase leo, and italicize both words when typed (underline each word by hand).',
  ],
  [
    'addition-precision',
    'significant-figures',
    'Addition uses decimal-place precision',
    'Report 12.1 + 0.24 with measurement-appropriate precision. Type the number.',
    ['12.3'],
    'The exact arithmetic sum is 12.34. Addition is limited by the tenths place of 12.1, so report 12.3.',
  ],
  [
    'exact-counts',
    'significant-figures',
    'Exact counts do not limit precision',
    'An exact count of 3 identical objects limits a measured calculation to one significant figure. Type true or false.',
    ['false'],
    'Exact counts and defined conversions do not introduce measurement uncertainty; measured quantities set the precision limit.',
  ],
  [
    'velocity-area',
    'motion-graphs',
    'Signed area of a velocity graph',
    'A cart has v = −3 m/s for 4 s. What signed displacement does its velocity–time graph represent? Type the value in metres.',
    ['-12'],
    'The rectangular signed area is (−3 m/s)(4 s) = −12 m. Distance travelled is 12 m under these conditions.',
  ],
  [
    'position-slope',
    'motion-graphs',
    'Slope of a position graph',
    'A straight position–time segment runs from (0 s, 2 m) to (4 s, 10 m). What velocity does its slope represent? Type the value in m/s.',
    ['2', '+2'],
    'Slope = (10−2) m / (4−0) s = +2 m/s. Position height itself is not velocity.',
  ],
];
for (const [id, concept, title, prompt, answer, explanation] of detailChecks) {
  const c = concepts.find((c) => c.id === concept)!;
  coverageItems.push({
    id: `detail-${id}`,
    course: c.course,
    unit: c.unit,
    concept,
    title,
    required: true,
    type:
      id === 'binomial-format'
        ? 'convention'
        : id.includes('slope') || id.includes('area')
          ? 'representation'
          : 'edge-item',
    sources: c.sources,
  });
  questions.push({
    id: `detail-${id}`,
    course: c.course,
    unit: c.unit,
    concepts: [concept],
    coverage: [`detail-${id}`],
    level: 'construction',
    purpose: 'coverage',
    format: 'text',
    archetype: `detail-${id}`,
    prompt,
    answer,
    explanation,
    hint: c.representation,
    diagnosis: concept,
    sources: c.sources,
    status: 'publishable',
  });
}
questions.find((q) => q.id === 'detail-addition-precision')!.precision =
  'decimal-places';

export const assignments: Assignment[] = [
  {
    id: 'kinematics-review',
    course: 'physics',
    edition: 'physics-fall-2026',
    teacher: 'Mr. Wadson',
    title: 'Kinematics review companion',
    assigned: '2026-10-04',
    status: 'current',
    summary:
      'Prepare for the Oct. 6 quiz by connecting signs, graphs and equation selection. This is an original study companion to the current review work.',
    tasks: [
      {
        id: 'signs',
        title: 'Set a direction convention',
        instructions:
          'Choose a positive axis. For each problem on your original sheet, write signed velocity and acceleration before inserting numbers.',
      },
      {
        id: 'graphs',
        title: 'Read each graph twice',
        instructions:
          'Name what the height, slope and area mean for the displayed axes. Explain a horizontal velocity segment without confusing it with rest.',
      },
      {
        id: 'equations',
        title: 'Choose, solve, audit',
        instructions:
          'List knowns and unknown. Select a constant-acceleration relation, rearrange, then check units, sign/direction and precision.',
      },
    ],
    concepts: [
      'vector-sign',
      'motion-graphs',
      'kinematic-equations',
      'free-fall',
    ],
    prerequisites: ['algebra-rearrangement', 'physics-units'],
    sources: ['vault-physics', 'atlas-original'],
    difficulty: ['sign reasoning', 'representation', 'equation selection'],
    rights: 'original-companion',
    originalUrl: 'https://cwadson.wixsite.com/mrwadson/physics-11-1',
    originalAvailability:
      'Use your class handouts; the teacher site is a resource library. No due date is confirmed.',
    notes:
      'The page-66 question-range instruction remains unverified and is not restated as a confirmed task.',
  },
  {
    id: 'electronic-structure',
    course: 'chemistry',
    edition: 'chemistry-fall-2026',
    teacher: 'Mrs. Cote',
    title: 'Hand In #13 · Electronic structure companion',
    assigned: '2026-10-04',
    status: 'current',
    summary:
      'Build the ideas and notation needed for the electronic-structure assignment. Complete the teacher’s original questions on your own sheet.',
    tasks: [
      {
        id: 'model',
        title: 'Connect shells, subshells and orbitals',
        instructions:
          'Explain the difference between a shell, subshell and orbital in your own words. Check s/p/d/f capacities without copying answers into assessed work.',
      },
      {
        id: 'notation',
        title: 'Practise fresh notation',
        instructions:
          'Use independent atlas examples to write full and core configurations. Add superscripts to check electron count.',
      },
      {
        id: 'submit',
        title: 'Complete and check the original',
        instructions:
          'Return to the original teacher assignment, work independently, and check all required sections. Confirm the due date in class.',
      },
    ],
    concepts: [
      'atomic-identity',
      'electron-configuration',
      'valence-electrons',
    ],
    prerequisites: ['atomic-identity'],
    sources: ['vault-chemistry', 'atlas-original'],
    difficulty: ['notation', 'electron counting'],
    rights: 'original-companion',
    originalUrl: 'https://mrstcote.wordpress.com/',
    originalAvailability:
      'Original paper handout; redistribution permission is not established. Teacher homepage is not a direct copy of the assignment.',
    notes:
      'Due-date field is unknown. No original question text or answer key is reproduced.',
  },
  {
    id: 'c17-research',
    course: 'life-sciences',
    edition: 'life-sciences-fall-2026',
    teacher: 'J. Bleecker',
    title: 'C17 · Origins research companion',
    assigned: '2026-09-22',
    status: 'current',
    summary:
      'Use the current Chapter 17 research block to explain fossil evidence, dating and the origin of cell complexity before the Oct. 7 test.',
    tasks: [
      {
        id: 'fossils',
        title: 'Reconstruct the fossil story',
        instructions:
          'Explain burial and preservation; compare sedimentary, igneous and metamorphic rock. Use superposition and index fossils to order events.',
      },
      {
        id: 'dating',
        title: 'Read the half-life model',
        instructions:
          'Work a new numerical example. State the closed-system assumptions, then distinguish a relative order from a numeric age.',
      },
      {
        id: 'origins',
        title: 'Separate evidence from claims',
        instructions:
          'Explain what Miller–Urey demonstrated, why microspheres are not living cells, and the evidence for bacterial origins of organelles.',
      },
      {
        id: 'evolution',
        title: 'Retrieve the expanded test scope',
        instructions:
          'Distinguish extinction, radiation, convergence, coevolution and patterns of pace. Review Hox genes as developmental patterning genes, using teacher notes.',
      },
    ],
    concepts: [
      'fossilization',
      'relative-dating',
      'half-life',
      'early-earth',
      'endosymbiosis',
      'evolution-patterns',
    ],
    prerequisites: ['phylogeny'],
    sources: ['vault-life', 'bleecker-calendar', 'atlas-original'],
    difficulty: [
      'mechanism explanation',
      'graph interpretation',
      'terminology',
    ],
    rights: 'original-companion',
    originalUrl: editions[1].resources[0],
    originalAvailability:
      'Follow the teacher site and your class notes. The research block runs through Oct. 6 (calendar end exclusive Oct. 7); this is not an inferred submission deadline.',
    notes:
      'Test Oct. 7 is confirmed by the live teacher calendar. Checklist completion records your self-report, not teacher submission.',
  },
  {
    id: 'greetings-practice',
    course: 'japanese',
    edition: 'japanese-fall-2026',
    teacher: 'McNeill-sensei',
    title: 'Basics & greetings · independent practice',
    assigned: '2026-09-23',
    status: 'current',
    summary:
      'Retrieve the current 18 expressions from a situation, then produce their written forms. This is independent practice rather than a new teacher-assigned deadline.',
    tasks: [
      {
        id: 'read',
        title: 'Read before translating',
        instructions:
          'Recognize the kana in a phrase, then recall the meaning without relying on rōmaji.',
      },
      {
        id: 'produce',
        title: 'Produce from a situation',
        instructions:
          'Choose morning/evening greetings, an introduction, a polite request and a thanks. Type them from memory, then practise handwriting using the teacher’s model.',
      },
      {
        id: 'contrast',
        title: 'Test one useful contrast',
        instructions:
          'After learning the phrases separately, compare polite attention-getting with apologizing. Explain when すみません is more appropriate than ごめんなさい.',
      },
    ],
    concepts: [
      'hiragana',
      'jp-ohayou',
      'jp-konnichiwa',
      'jp-sumimasen',
      'jp-arigatou',
    ],
    prerequisites: ['hiragana', 'mora'],
    sources: ['vault-japanese', 'atlas-original'],
    difficulty: ['recall', 'situation fit', 'script production'],
    rights: 'original-companion',
    originalUrl: 'https://marugoto.jpf.go.jp/en/e-learning/index.html',
    originalAvailability:
      'Use the teacher’s vocabulary/kana handouts for class expectations. No new quiz date has been inferred.',
    notes:
      'AI/translator assistance must remain on the learning side. Do not use it to produce submitted class work.',
  },
];

const event = (
  id: string,
  course: string | undefined,
  title: string,
  type: ScheduleEvent['type'],
  start: string | undefined,
  notes: string,
  confidence: ScheduleEvent['confidence'],
  source: string,
  ids: string[] = [],
  end?: string,
): ScheduleEvent => ({
  id,
  course,
  edition: course ? `${course}-fall-2026` : undefined,
  title,
  type,
  start,
  end,
  notes,
  confidence,
  status: start ? 'scheduled' : 'date-unconfirmed',
  sources: [source],
  verified: snapshot.date,
  concepts: ids,
  public: true,
});
export const schedule: ScheduleEvent[] = [
  event(
    'ni-sept28',
    undefined,
    'Indigenous Day of Learning · no classes',
    'holiday',
    '2026-09-28',
    'District non-instructional day.',
    'teacher-confirmed',
    'district-calendar',
  ),
  event(
    'truth-sept30',
    undefined,
    'Truth and Reconciliation Day',
    'holiday',
    '2026-09-30',
    'School holiday in the approved district calendar.',
    'teacher-confirmed',
    'district-calendar',
  ),
  event(
    'thanksgiving',
    undefined,
    'Thanksgiving · no classes',
    'holiday',
    '2026-10-12',
    'School holiday in the approved district calendar.',
    'teacher-confirmed',
    'district-calendar',
  ),
  event(
    'remembrance',
    undefined,
    'Remembrance Day · no classes',
    'holiday',
    '2026-11-11',
    'School holiday in the approved district calendar.',
    'teacher-confirmed',
    'district-calendar',
  ),
  event(
    'chem-quiz-oct5',
    'chemistry',
    'Periodic trends & bonding quiz',
    'quiz',
    '2026-10-05',
    '15 multiple-choice questions; notes through page 24. Later Lewis/VSEPR material is excluded unless the teacher changes the scope.',
    'student-confirmed',
    'vault-chemistry',
    [
      'periodic-trends',
      'electronegativity',
      'bond-types',
      'intermolecular-forces',
    ],
  ),
  event(
    'physics-quiz-oct6',
    'physics',
    'Kinematics quiz',
    'quiz',
    '2026-10-06',
    'Latest source supersedes the older Oct. 6 unit-test date. Use the permitted formula sheet.',
    'student-confirmed',
    'vault-physics',
    ['vector-sign', 'motion-graphs', 'kinematic-equations', 'free-fall'],
  ),
  {
    ...event(
      'physics-test-unconfirmed',
      'physics',
      'Kinematics unit test',
      'test',
      undefined,
      'Oct. 7 or Oct. 9; exact day not confirmed. Check the classroom board.',
      'unverified',
      'vault-physics',
      ['kinematic-equations', 'free-fall'],
    ),
    dateNote: 'Oct. 7 or Oct. 9 · awaiting confirmation',
  },
  event(
    'c17-test-oct7',
    'life-sciences',
    'C17 · Origins & fossil record test',
    'test',
    '2026-10-07',
    'Teacher scope includes fossils, rock types, dating, geologic time, early Earth, Miller–Urey, microspheres, endosymbiosis and evolutionary patterns.',
    'teacher-confirmed',
    'bleecker-calendar',
    [
      'fossilization',
      'relative-dating',
      'half-life',
      'geologic-time',
      'early-earth',
      'endosymbiosis',
      'evolution-patterns',
    ],
  ),
  event(
    'c19-research',
    'life-sciences',
    'C19 · Viruses, bacteria & disease research',
    'research',
    '2026-10-06',
    'Teacher research block. Chapter 19 learning pages have not yet been reviewed.',
    'teacher-confirmed',
    'bleecker-calendar',
    [],
    '2026-10-20',
  ),
  event(
    'c19-quiz-oct9',
    'life-sciences',
    'C19 · Sections 19.1/19.2 quiz',
    'quiz',
    '2026-10-09',
    'Live source now provides a viruses/bacteria study guide. Original atlas coverage for this chapter is pending; use the teacher guide.',
    'teacher-confirmed',
    'bleecker-calendar',
  ),
  event(
    'chem-test-oct16',
    'chemistry',
    'Chemistry unit test',
    'test',
    '2026-10-16',
    'Date confirmed by Jovan; exact teacher test boundary is not confirmed. Taught material is not a guarantee of assessment scope.',
    'student-confirmed',
    'vault-chemistry',
    ['periodic-trends', 'lewis-structures', 'vsepr'],
  ),
  event(
    'anime-project',
    'japanese',
    'Anime Project presentation',
    'project',
    '2026-11-20',
    'Date recorded in the course outline update. Exact rubric and topic requirements have not been supplied.',
    'student-confirmed',
    'vault-japanese',
  ),
  event(
    'pro-d-oct23',
    undefined,
    'Pro-D day',
    'holiday',
    '2026-10-23',
    'No classes; teacher calendar snapshot.',
    'teacher-confirmed',
    'bleecker-calendar',
  ),
  event(
    'pro-d-nov27',
    undefined,
    'Pro-D day',
    'holiday',
    '2026-11-27',
    'No classes; teacher calendar snapshot.',
    'teacher-confirmed',
    'bleecker-calendar',
  ),
  event(
    'winter-break',
    undefined,
    'Winter break',
    'holiday',
    '2026-12-21',
    'Teacher calendar ends Jan. 2 exclusively: last break date is Jan. 1.',
    'teacher-confirmed',
    'bleecker-calendar',
    [],
    '2027-01-01',
  ),
];
export const findCourse = (id: string) => courses.find((c) => c.id === id)!;
export const findEdition = (id: string) =>
  editions.find((e) => e.course === id)!;
export const findConcept = (id: string) => concepts.find((c) => c.id === id)!;
